export const transactions = [
  {
    id: 1,
    title: 'Jamia Company pvt. ltd.',
    amount: 8011,
    balance: 133004,
    time: '10:08 PM',
    date: '12-Feb-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Removal of Monitoring Device from Diaphragm, Via Natural or Artificial Opening Endoscopic',
  },
  {
    id: 2,
    title: 'Rhynoodle Enterprises pvt. ltd.',
    amount: 5165,
    balance: 158158,
    time: '8:18 PM',
    date: '04-Apr-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment: 'Sensorineural Acuity Level Assessment using Sound Field / Booth',
  },
  {
    id: 3,
    title: 'Fivechat Company pvt. ltd.',
    amount: 9433,
    balance: 142336,
    time: '4:14 PM',
    date: '02-Mar-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Repair Right Humeral Shaft, Percutaneous Endoscopic Approach',
  },
  {
    id: 4,
    title: 'Edgeblab Organization pvt. ltd.',
    amount: 8837,
    balance: 28737,
    time: '9:14 PM',
    date: '11-Jul-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Dilation of Left Kidney Pelvis, Percutaneous Endoscopic Approach',
  },
  {
    id: 5,
    title: 'Demivee Enterprises pvt. ltd.',
    amount: 9693,
    balance: 140600,
    time: '10:16 AM',
    date: '01-Sep-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Dilation of Ileocecal Valve with Intraluminal Device, Open Approach',
  },
  {
    id: 6,
    title: 'Yata Enterprises pvt. ltd.',
    amount: 8278,
    balance: 114548,
    time: '7:46 PM',
    date: '25-Dec-2022',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Bypass Left Subclavian Artery to Left Lower Arm Artery with Autologous Venous Tissue, Open Approach',
  },
  {
    id: 7,
    title: 'Twimbo Company pvt. ltd.',
    amount: 3429,
    balance: 149851,
    time: '8:24 PM',
    date: '06-Mar-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Release Inferior Mesenteric Vein, Open Approach',
  },
  {
    id: 8,
    title: 'Myworks Company pvt. ltd.',
    amount: 9397,
    balance: 70920,
    time: '5:11 AM',
    date: '05-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment: 'Insertion of Monitoring Device into Stomach, Open Approach',
  },
  {
    id: 9,
    title: 'Midel Organization pvt. ltd.',
    amount: 3525,
    balance: 136457,
    time: '1:52 PM',
    date: '22-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment: 'Drainage of Azygos Vein, Percutaneous Approach',
  },
  {
    id: 10,
    title: 'Trunyx Enterprises pvt. ltd.',
    amount: 4943,
    balance: 52172,
    time: '2:11 PM',
    date: '10-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Replacement of Right Upper Eyelid with Nonautologous Tissue Substitute, External Approach',
  },
  {
    id: 11,
    title: 'Pixope Enterprises pvt. ltd.',
    amount: 7067,
    balance: 64062,
    time: '2:02 PM',
    date: '24-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Drainage of Sacral Sympathetic Nerve with Drainage Device, Percutaneous Endoscopic Approach',
  },
  {
    id: 12,
    title: 'Katz Organization pvt. ltd.',
    amount: 1237,
    balance: 80912,
    time: '12:55 AM',
    date: '24-Sep-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Extirpation of Matter from Abdominal Aorta, Bifurcation, Percutaneous Endoscopic Approach',
  },
  {
    id: 13,
    title: 'Rhyloo Enterprises pvt. ltd.',
    amount: 6087,
    balance: 92108,
    time: '4:30 PM',
    date: '09-Jun-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Replacement of Right Fibula with Synthetic Substitute, Percutaneous Endoscopic Approach',
  },
  {
    id: 14,
    title: 'Demizz Organization pvt. ltd.',
    amount: 8244,
    balance: 198211,
    time: '4:41 PM',
    date: '18-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Replacement of Left Hip Joint with Ceramic Synthetic Substitute, Cemented, Open Approach',
  },
  {
    id: 15,
    title: 'Wikivu Enterprises pvt. ltd.',
    amount: 2323,
    balance: 194456,
    time: '6:29 PM',
    date: '19-Jul-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Irrigation of Upper GI using Irrigating Substance, Via Natural or Artificial Opening',
  },
  {
    id: 16,
    title: 'Jaxnation Organization pvt. ltd.',
    amount: 6269,
    balance: 98929,
    time: '4:14 PM',
    date: '23-Jan-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Removal of Drainage Device from Right Tarsal Joint, Percutaneous Approach',
  },
  {
    id: 17,
    title: 'Realcube Company pvt. ltd.',
    amount: 2266,
    balance: 35981,
    time: '11:25 AM',
    date: '30-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Bypass Abdominal Aorta to Right External Iliac Artery with Autologous Arterial Tissue, Open Approach',
  },
  {
    id: 18,
    title: 'Flashpoint Organization pvt. ltd.',
    amount: 6033,
    balance: 115906,
    time: '8:31 AM',
    date: '09-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Supplement Left Ureter with Autologous Tissue Substitute, Via Natural or Artificial Opening',
  },
  {
    id: 19,
    title: 'Vitz Enterprises pvt. ltd.',
    amount: 7094,
    balance: 117208,
    time: '5:21 PM',
    date: '20-Jun-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Bypass Left Foot Vein to Lower Vein, Percutaneous Endoscopic Approach',
  },
  {
    id: 20,
    title: 'Dynazzy Company pvt. ltd.',
    amount: 2190,
    balance: 174696,
    time: '12:46 PM',
    date: '04-Oct-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Drainage of Right Elbow Bursa and Ligament with Drainage Device, Percutaneous Approach',
  },
  {
    id: 21,
    title: 'Dazzlesphere Enterprises pvt. ltd.',
    amount: 3129,
    balance: 19229,
    time: '12:16 PM',
    date: '13-Dec-2022',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Dilation of Right Renal Vein, Percutaneous Endoscopic Approach',
  },
  {
    id: 22,
    title: 'Flashspan Organization pvt. ltd.',
    amount: 1242,
    balance: 125550,
    time: '9:25 PM',
    date: '09-Nov-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Bypass Coronary Artery, Two Arteries from Coronary Artery with Zooplastic Tissue, Percutaneous Endoscopic Approach',
  },
  {
    id: 23,
    title: 'Quatz Company pvt. ltd.',
    amount: 3721,
    balance: 85086,
    time: '5:08 AM',
    date: '01-May-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment: 'Excision of Thoracic Duct, Percutaneous Approach, Diagnostic',
  },
  {
    id: 24,
    title: 'Meeveo Enterprises pvt. ltd.',
    amount: 5529,
    balance: 156397,
    time: '6:39 PM',
    date: '04-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Immobilization of Left Foot using Other Device',
  },
  {
    id: 25,
    title: 'Demimbu Organization pvt. ltd.',
    amount: 9378,
    balance: 98363,
    time: '12:17 AM',
    date: '27-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Alteration of Bilateral External Ear with Synthetic Substitute, Percutaneous Approach',
  },
  {
    id: 26,
    title: 'Skyvu Organization pvt. ltd.',
    amount: 3578,
    balance: 135193,
    time: '8:03 AM',
    date: '28-Jul-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Replacement of Left Vocal Cord with Nonautologous Tissue Substitute, Via Natural or Artificial Opening',
  },
  {
    id: 27,
    title: 'Katz Organization pvt. ltd.',
    amount: 2355,
    balance: 160119,
    time: '12:14 PM',
    date: '03-Sep-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment: 'Reattachment of Right Elbow Region, Open Approach',
  },
  {
    id: 28,
    title: 'Twitterworks Enterprises pvt. ltd.',
    amount: 9469,
    balance: 168087,
    time: '1:09 PM',
    date: '29-Jul-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Introduction of Other Antineoplastic into Male Reproductive, Percutaneous Approach',
  },
  {
    id: 29,
    title: 'Buzzbean Enterprises pvt. ltd.',
    amount: 6054,
    balance: 162648,
    time: '4:48 AM',
    date: '28-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Destruction of Left Lacrimal Duct, Percutaneous Approach',
  },
  {
    id: 30,
    title: 'Yodoo Enterprises pvt. ltd.',
    amount: 9543,
    balance: 12580,
    time: '8:52 PM',
    date: '11-Jan-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Supplement Left Acromioclavicular Joint with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
  },
  {
    id: 31,
    title: 'Ailane Company pvt. ltd.',
    amount: 7302,
    balance: 155022,
    time: '9:00 PM',
    date: '10-Sep-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Repair Right Thorax Muscle, Percutaneous Approach',
  },
  {
    id: 32,
    title: 'Oyoloo Organization pvt. ltd.',
    amount: 9645,
    balance: 102608,
    time: '2:31 PM',
    date: '09-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment: 'Drainage of Left Hand Vein, Percutaneous Endoscopic Approach',
  },
  {
    id: 33,
    title: 'Divanoodle Organization pvt. ltd.',
    amount: 7782,
    balance: 125678,
    time: '9:50 PM',
    date: '06-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment: 'Change Drainage Device in Upper Back, External Approach',
  },
  {
    id: 34,
    title: 'Ntags Organization pvt. ltd.',
    amount: 1098,
    balance: 182837,
    time: '9:17 PM',
    date: '20-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Removal of Extraluminal Device from Epididymis and Spermatic Cord, Via Natural or Artificial Opening Endoscopic',
  },
  {
    id: 35,
    title: 'Twitterbeat Company pvt. ltd.',
    amount: 3301,
    balance: 34837,
    time: '8:03 AM',
    date: '27-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment: 'Repair Innominate Artery, Percutaneous Endoscopic Approach',
  },
  {
    id: 36,
    title: 'Centidel Organization pvt. ltd.',
    amount: 8180,
    balance: 7677,
    time: '3:54 PM',
    date: '17-Jul-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Extirpation of Matter from Right Lower Lung Lobe, Percutaneous Endoscopic Approach',
  },
  {
    id: 37,
    title: 'Thoughtstorm Organization pvt. ltd.',
    amount: 2838,
    balance: 92849,
    time: '12:47 AM',
    date: '09-Feb-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Destruction of Right Radial Artery, Percutaneous Endoscopic Approach',
  },
  {
    id: 38,
    title: 'Dabfeed Organization pvt. ltd.',
    amount: 2112,
    balance: 99966,
    time: '5:21 PM',
    date: '25-Jun-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Extirpation of Matter from Hemiazygos Vein, Percutaneous Endoscopic Approach',
  },
  {
    id: 39,
    title: 'Viva Organization pvt. ltd.',
    amount: 6071,
    balance: 100888,
    time: '6:51 PM',
    date: '19-May-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Computerized Tomography (CT Scan) of Right Pulmonary Vein using Intravascular Optical Coherence',
  },
  {
    id: 40,
    title: 'Izio Enterprises pvt. ltd.',
    amount: 4033,
    balance: 21303,
    time: '3:21 AM',
    date: '11-Sep-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Repair Nervous System in Products of Conception, Percutaneous Approach',
  },
  {
    id: 41,
    title: 'Realcube Organization pvt. ltd.',
    amount: 6825,
    balance: 9574,
    time: '5:32 PM',
    date: '19-Nov-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment: 'Insertion of Radioactive Element into Lower Jaw, Open Approach',
  },
  {
    id: 42,
    title: 'Quinu Company pvt. ltd.',
    amount: 2919,
    balance: 11598,
    time: '2:15 AM',
    date: '30-Jul-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Muscle Performance Treatment of Musculoskeletal System - Head and Neck using Prosthesis',
  },
  {
    id: 43,
    title: 'Jabberstorm Enterprises pvt. ltd.',
    amount: 5480,
    balance: 67147,
    time: '4:56 PM',
    date: '26-May-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Removal of Drainage Device from Left Elbow Joint, Percutaneous Endoscopic Approach',
  },
  {
    id: 44,
    title: 'Babbleset Company pvt. ltd.',
    amount: 2140,
    balance: 40377,
    time: '2:55 PM',
    date: '16-Jul-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Fluoroscopy of Sacroiliac Joints using High Osmolar Contrast',
  },
  {
    id: 45,
    title: 'Leexo Company pvt. ltd.',
    amount: 1098,
    balance: 56282,
    time: '7:04 AM',
    date: '30-Mar-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Transfer Face Subcutaneous Tissue and Fascia, Percutaneous Approach',
  },
  {
    id: 46,
    title: 'Skinte Company pvt. ltd.',
    amount: 1530,
    balance: 98690,
    time: '4:31 PM',
    date: '11-May-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Dilation of Coronary Artery, Two Arteries with Four or More Drug-eluting Intraluminal Devices, Percutaneous Endoscopic Approach',
  },
  {
    id: 47,
    title: 'Zazio Company pvt. ltd.',
    amount: 5191,
    balance: 29879,
    time: '6:10 AM',
    date: '29-Nov-2022',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Extirpation of Matter from Sacral Nerve, Open Approach',
  },
  {
    id: 48,
    title: 'Gabvine Enterprises pvt. ltd.',
    amount: 5786,
    balance: 182458,
    time: '3:22 AM',
    date: '11-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Transfer Glossopharyngeal Nerve to Oculomotor Nerve, Open Approach',
  },
  {
    id: 49,
    title: 'Gabtune Organization pvt. ltd.',
    amount: 4452,
    balance: 152497,
    time: '8:52 AM',
    date: '27-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Insertion of Other Device into Right Knee Region, Open Approach',
  },
  {
    id: 50,
    title: 'Wikizz Enterprises pvt. ltd.',
    amount: 9684,
    balance: 136970,
    time: '12:58 AM',
    date: '12-Oct-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Bypass Middle Esophagus to Cutaneous with Autologous Tissue Substitute, Via Natural or Artificial Opening Endoscopic',
  },
  {
    id: 51,
    title: 'Blogspan Enterprises pvt. ltd.',
    amount: 9160,
    balance: 135809,
    time: '5:10 AM',
    date: '04-Mar-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment: 'Destruction of Left Lower Eyelid, External Approach',
  },
  {
    id: 52,
    title: 'Shufflester Company pvt. ltd.',
    amount: 7952,
    balance: 183464,
    time: '4:44 AM',
    date: '25-Feb-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Reposition Left Femoral Shaft with External Fixation Device, Percutaneous Endoscopic Approach',
  },
  {
    id: 53,
    title: 'Mybuzz Organization pvt. ltd.',
    amount: 9318,
    balance: 164286,
    time: '2:30 AM',
    date: '06-Sep-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Beam Radiation of Maxilla using Photons 1 - 10 MeV',
  },
  {
    id: 54,
    title: 'Aibox Organization pvt. ltd.',
    amount: 5636,
    balance: 72074,
    time: '7:50 AM',
    date: '25-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Occlusion of Ileocecal Valve with Extraluminal Device, Open Approach',
  },
  {
    id: 55,
    title: 'Oba Enterprises pvt. ltd.',
    amount: 3372,
    balance: 1331,
    time: '6:01 AM',
    date: '09-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Revision of Synthetic Substitute in Stomach, Percutaneous Approach',
  },
  {
    id: 56,
    title: 'Demizz Organization pvt. ltd.',
    amount: 4158,
    balance: 183633,
    time: '8:48 AM',
    date: '08-Aug-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Low Dose Rate (LDR) Brachytherapy of Pituitary Gland using Iodine 125 (I-125)',
  },
  {
    id: 57,
    title: 'Lazz Enterprises pvt. ltd.',
    amount: 9480,
    balance: 142746,
    time: '7:43 AM',
    date: '19-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Destruction of Right Humeral Shaft, Open Approach',
  },
  {
    id: 58,
    title: 'Photobug Company pvt. ltd.',
    amount: 4455,
    balance: 101806,
    time: '8:19 AM',
    date: '21-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Computerized Tomography (CT Scan) of Right Ribs using Other Contrast',
  },
  {
    id: 59,
    title: 'Skippad Organization pvt. ltd.',
    amount: 9122,
    balance: 62781,
    time: '12:46 AM',
    date: '22-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Extraction of Acoustic Nerve, Percutaneous Endoscopic Approach',
  },
  {
    id: 60,
    title: 'Centizu Company pvt. ltd.',
    amount: 9059,
    balance: 47864,
    time: '4:19 AM',
    date: '31-Jul-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Drainage of Left Scapula, Percutaneous Endoscopic Approach, Diagnostic',
  },
  {
    id: 61,
    title: 'Youopia Company pvt. ltd.',
    amount: 4353,
    balance: 184500,
    time: '7:19 AM',
    date: '10-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Repair Right Upper Femur, External Approach',
  },
  {
    id: 62,
    title: 'Kazio Organization pvt. ltd.',
    amount: 8169,
    balance: 163782,
    time: '7:31 AM',
    date: '17-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Bypass Descending Colon to Rectum with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
  },
  {
    id: 63,
    title: 'Flashpoint Enterprises pvt. ltd.',
    amount: 6950,
    balance: 199057,
    time: '3:09 PM',
    date: '23-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Destruction of Bilateral Seminal Vesicles, Open Approach',
  },
  {
    id: 64,
    title: 'Babbleopia Organization pvt. ltd.',
    amount: 5582,
    balance: 42577,
    time: '7:22 AM',
    date: '31-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Restriction of Jejunum with Extraluminal Device, Percutaneous Endoscopic Approach',
  },
  {
    id: 65,
    title: 'Yadel Organization pvt. ltd.',
    amount: 7631,
    balance: 111447,
    time: '5:11 PM',
    date: '24-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Drainage of Trachea with Drainage Device, Percutaneous Approach',
  },
  {
    id: 66,
    title: 'Photojam Enterprises pvt. ltd.',
    amount: 2182,
    balance: 146110,
    time: '4:42 AM',
    date: '07-Nov-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Removal of Synthetic Substitute from Cervical Vertebra, Percutaneous Endoscopic Approach',
  },
  {
    id: 67,
    title: 'Demizz Enterprises pvt. ltd.',
    amount: 1319,
    balance: 127967,
    time: '5:39 PM',
    date: '07-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Release Right Upper Leg Muscle, Open Approach',
  },
  {
    id: 68,
    title: 'Photobug Company pvt. ltd.',
    amount: 7105,
    balance: 70678,
    time: '3:21 PM',
    date: '10-Oct-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment:
      'Division of Head and Neck Sympathetic Nerve, Percutaneous Approach',
  },
  {
    id: 69,
    title: 'Jabberbean Organization pvt. ltd.',
    amount: 7110,
    balance: 124403,
    time: '7:30 PM',
    date: '07-Nov-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Removal of Intraluminal Device from Hepatobiliary Duct, Via Natural or Artificial Opening',
  },
  {
    id: 70,
    title: 'Tazzy Company pvt. ltd.',
    amount: 7606,
    balance: 49356,
    time: '10:36 PM',
    date: '01-Sep-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment: 'Change Intermittent Pressure Device on Left Lower Extremity',
  },
  {
    id: 71,
    title: 'Topicstorm Organization pvt. ltd.',
    amount: 1368,
    balance: 35627,
    time: '3:02 PM',
    date: '28-Apr-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Removal of Synthetic Substitute from Mouth and Throat, Percutaneous Approach',
  },
  {
    id: 72,
    title: 'Flipbug Enterprises pvt. ltd.',
    amount: 2466,
    balance: 42609,
    time: '10:13 PM',
    date: '26-Aug-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment: 'Repair Left Upper Arm, Percutaneous Endoscopic Approach',
  },
  {
    id: 73,
    title: 'Photospace Company pvt. ltd.',
    amount: 1260,
    balance: 71750,
    time: '6:15 PM',
    date: '11-Feb-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Dilation of Left Upper Lobe Bronchus with Intraluminal Device, Open Approach',
  },
  {
    id: 74,
    title: 'Yakidoo Organization pvt. ltd.',
    amount: 6587,
    balance: 28289,
    time: '2:03 PM',
    date: '11-Nov-2022',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment: 'Repair Cecum, Percutaneous Approach',
  },
  {
    id: 75,
    title: 'Snaptags Enterprises pvt. ltd.',
    amount: 6040,
    balance: 138191,
    time: '4:54 AM',
    date: '20-Jun-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Insertion of Infusion Device into Thoracolumbar Vertebral Joint, Percutaneous Approach',
  },
  {
    id: 76,
    title: 'Buzzster Company pvt. ltd.',
    amount: 8066,
    balance: 185465,
    time: '1:22 PM',
    date: '13-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Supplement Left Retina with Nonautologous Tissue Substitute, Percutaneous Approach',
  },
  {
    id: 77,
    title: 'Ainyx Organization pvt. ltd.',
    amount: 2862,
    balance: 22359,
    time: '4:41 PM',
    date: '23-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Bypass Left Subclavian Artery to Right Extracranial Artery with Autologous Venous Tissue, Open Approach',
  },
  {
    id: 78,
    title: 'Zoombeat Company pvt. ltd.',
    amount: 7270,
    balance: 103153,
    time: '6:42 AM',
    date: '14-Jun-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment: 'Dilation of Superior Mesenteric Vein, Open Approach',
  },
  {
    id: 79,
    title: 'Brightdog Company pvt. ltd.',
    amount: 3031,
    balance: 28792,
    time: '10:14 AM',
    date: '24-Apr-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Replacement of Left Brachial Artery with Synthetic Substitute, Percutaneous Endoscopic Approach',
  },
  {
    id: 80,
    title: 'Kamba Organization pvt. ltd.',
    amount: 1438,
    balance: 86803,
    time: '8:15 PM',
    date: '13-Aug-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Insertion of Infusion Device into Fallopian Tube, Open Approach',
  },
  {
    id: 81,
    title: 'Flashspan Enterprises pvt. ltd.',
    amount: 8237,
    balance: 51442,
    time: '12:14 PM',
    date: '22-Feb-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Revision of Internal Fixation Device in Left Shoulder Joint, External Approach',
  },
  {
    id: 82,
    title: 'Camimbo Enterprises pvt. ltd.',
    amount: 6151,
    balance: 88866,
    time: '9:42 PM',
    date: '18-Jan-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashIn',
    comment: 'Bypass Right Foot Vein to Lower Vein, Open Approach',
  },
  {
    id: 83,
    title: 'Feedfire Enterprises pvt. ltd.',
    amount: 2358,
    balance: 57221,
    time: '12:48 PM',
    date: '24-Dec-2022',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Revision of Autologous Tissue Substitute in Nasal Bone, Percutaneous Endoscopic Approach',
  },
  {
    id: 84,
    title: 'Quatz Enterprises pvt. ltd.',
    amount: 6717,
    balance: 68670,
    time: '6:42 AM',
    date: '06-Mar-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Removal of Monitoring Device from Hepatobiliary Duct, Percutaneous Approach',
  },
  {
    id: 85,
    title: 'Thoughtstorm Organization pvt. ltd.',
    amount: 3628,
    balance: 6950,
    time: '6:57 AM',
    date: '05-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Transfusion of Autologous White Cells into Central Artery, Open Approach',
  },
  {
    id: 86,
    title: 'Fivechat Enterprises pvt. ltd.',
    amount: 8164,
    balance: 25406,
    time: '12:30 PM',
    date: '31-May-2023',
    paymentMode: 'Cash',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Bypass Lower Esophagus to Stomach with Nonautologous Tissue Substitute, Open Approach',
  },
  {
    id: 87,
    title: 'Meevee Organization pvt. ltd.',
    amount: 9359,
    balance: 25686,
    time: '4:41 PM',
    date: '10-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Bypass Left Inner Ear to Endolymphatic with Nonautologous Tissue Substitute, Open Approach',
  },
  {
    id: 88,
    title: 'Pixonyx Enterprises pvt. ltd.',
    amount: 9972,
    balance: 40190,
    time: '5:45 AM',
    date: '04-Apr-2023',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashOut',
    comment:
      'Insertion of Multiple Array Rechargeable Stimulator Generator into Chest Subcutaneous Tissue and Fascia, Open Approach',
  },
  {
    id: 89,
    title: 'Muxo Enterprises pvt. ltd.',
    amount: 3971,
    balance: 155284,
    time: '5:05 PM',
    date: '14-Jul-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment:
      'Supplement Right Shoulder Joint with Nonautologous Tissue Substitute, Open Approach',
  },
  {
    id: 90,
    title: 'Edgetag Enterprises pvt. ltd.',
    amount: 5252,
    balance: 69586,
    time: '10:29 AM',
    date: '03-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Insertion of Intraluminal Device into Right Subclavian Vein, Percutaneous Endoscopic Approach',
  },
  {
    id: 91,
    title: 'Aimbu Enterprises pvt. ltd.',
    amount: 9425,
    balance: 17011,
    time: '2:39 PM',
    date: '18-Feb-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment: 'Detachment at Left Foot, Complete 4th Ray, Open Approach',
  },
  {
    id: 92,
    title: 'Eazzy Enterprises pvt. ltd.',
    amount: 3389,
    balance: 180665,
    time: '5:11 PM',
    date: '29-Dec-2022',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Computerized Tomography (CT Scan) of Thyroid Gland using Low Osmolar Contrast',
  },
  {
    id: 93,
    title: 'Roodel Organization pvt. ltd.',
    amount: 5634,
    balance: 79304,
    time: '9:24 AM',
    date: '29-Nov-2022',
    paymentMode: 'Online',
    paymentProvider: 'PhonePe',
    type: 'CashIn',
    comment:
      'Revision of Intraluminal Device in Great Vessel, Percutaneous Endoscopic Approach',
  },
  {
    id: 94,
    title: 'Jabberbean Company pvt. ltd.',
    amount: 2305,
    balance: 3277,
    time: '3:07 PM',
    date: '05-Dec-2022',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment: 'Reattachment of Left Hand, Open Approach',
  },
  {
    id: 95,
    title: 'Lajo Organization pvt. ltd.',
    amount: 6917,
    balance: 81639,
    time: '1:23 AM',
    date: '21-Mar-2023',
    paymentMode: 'Online',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Change Packing Material on Right Toe',
  },
  {
    id: 96,
    title: 'Demizz Company pvt. ltd.',
    amount: 3725,
    balance: 1453,
    time: '11:36 AM',
    date: '05-Mar-2023',
    paymentMode: 'Cash',
    paymentProvider: 'Paytm',
    type: 'CashOut',
    comment:
      'Dilation of Intracranial Artery with Intraluminal Device, Open Approach',
  },
  {
    id: 97,
    title: 'Browsecat Enterprises pvt. ltd.',
    amount: 4444,
    balance: 64340,
    time: '9:45 AM',
    date: '22-Jan-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashOut',
    comment:
      'Revision of Infusion Device in Great Vessel, Percutaneous Approach',
  },
  {
    id: 98,
    title: 'Buzzbean Company pvt. ltd.',
    amount: 2063,
    balance: 54476,
    time: '8:19 PM',
    date: '07-Oct-2023',
    paymentMode: 'Online',
    paymentProvider: 'Bank',
    type: 'CashIn',
    comment:
      'Supplement Right Abdomen Muscle with Nonautologous Tissue Substitute, Percutaneous Endoscopic Approach',
  },
  {
    id: 99,
    title: 'Skyvu Organization pvt. ltd.',
    amount: 8280,
    balance: 80321,
    time: '11:30 AM',
    date: '31-May-2023',
    paymentMode: 'Cash',
    paymentProvider: 'GPay',
    type: 'CashOut',
    comment: 'Removal of Cast on Left Finger',
  },
  {
    id: 100,
    title: 'Kaymbo Organization pvt. ltd.',
    amount: 2498,
    balance: 81638,
    time: '11:22 AM',
    date: '18-Jan-2023',
    paymentMode: 'Online',
    paymentProvider: 'Paytm',
    type: 'CashIn',
    comment:
      'Dilation of Left Common Carotid Artery with Four or More Drug-eluting Intraluminal Devices, Open Approach',
  },
];
